# -*- coding: utf-8 -*-


MY_NAME = "settingsd"

FUNCTIONS_DIR = "functions"
ACTIONS_DIR = "actions"
CONFIGS_DIR = "configs"
CONFIG_FILE_POSTFIX = ".conf"


SERVICE_BUS_TYPE_SYSTEM = "system"
SERVICE_BUS_TYPE_SESSION = "session"
ALL_SERVICE_BUS_TYPES_LIST = (
	SERVICE_BUS_TYPE_SYSTEM,
	SERVICE_BUS_TYPE_SESSION
)

LOG_LEVEL_INFO = 0
LOG_LEVEL_VERBOSE = 1
LOG_LEVEL_DEBUG = 2
ALL_LOG_LEVELS_LIST = (
	LOG_LEVEL_INFO,
	LOG_LEVEL_VERBOSE,
	LOG_LEVEL_DEBUG
)


DEFAULT_SERVICE_NAME = "org.etersoft.%s" % (MY_NAME)
DEFAULT_SERVICE_PATH = "/org/etersoft/%s" % (MY_NAME)
DEFAULT_SERVICE_BUS_TYPE = SERVICE_BUS_TYPE_SYSTEM
DEFAULT_LOG_LEVEL = LOG_LEVEL_INFO

