MY_NAME = "settingsd"

PLUGINS_DIR = "plugins"
CONFIGS_DIR = "configs"
CONFIG_FILE_POSTFIX = ".conf"

CONFIG_SERVICE_BUS_TYPE_SYSTEM = "system"
CONFIG_SERVICE_BUS_TYPE_SESSION = "session"
CONFIG_VALID_SERVICE_BUS_TYPES_LIST = (
	CONFIG_SERVICE_BUS_TYPE_SYSTEM,
	CONFIG_SERVICE_BUS_TYPE_SESSION
)

DEFAULT_CONFIG_SERVICE_NAME = "org.etersoft.%s" % (MY_NAME)
DEFAULT_CONFIG_SERVICE_PATH = "/org/etersoft/%s" % (MY_NAME)
DEFAULT_CONFIG_SERVICE_BUS_TYPE = CONFIG_SERVICE_BUS_TYPE_SYSTEM


